# Generated by Django 6.0 on 2025-12-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена (в месяц)')),
                ('area', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Площадь (м²)')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/', verbose_name='Фото')),
                ('rental_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Частный дом'), ('room', 'Комната')], default='apartment', max_length=20, verbose_name='Тип жилья')),
                ('is_available', models.BooleanField(default=True, verbose_name='Свободно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Объект аренды',
                'verbose_name_plural': 'Объекты аренды',
            },
        ),
    ]
