# Generated by Django 6.0 on 2025-12-21 07:51

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('icon', models.CharField(blank=True, help_text='Название иконки для фронтенда', max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Переопределение цены на эту дату', max_digits=10, null=True, verbose_name='Особая цена')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Заметки')),
                ('source', models.CharField(choices=[('manual', 'Ручное управление'), ('ical', 'iCal синхронизация'), ('booking', 'Бронирование')], default='manual', max_length=50, verbose_name='Источник')),
                ('external_id', models.CharField(blank=True, help_text='ID события во внешнем календаре', max_length=100, verbose_name='Внешний ID')),
            ],
            options={
                'verbose_name': 'Доступность',
                'verbose_name_plural': 'Доступности',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Заезд')),
                ('check_out', models.DateField(verbose_name='Выезд')),
                ('guests_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во гостей')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('owner_response', models.BooleanField(blank=True, help_text='True - принято, False - отклонено', null=True, verbose_name='Ответ владельца')),
                ('owner_response_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ответа')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('refunded', 'Возвращено')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('special_requests', models.TextField(blank=True, verbose_name='Особые пожелания')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_guest', to=settings.AUTH_USER_MODEL, verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ICalSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Ссылка на iCal календарь', verbose_name='iCal URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('sync_frequency', models.IntegerField(default=60, help_text='Как часто обновлять календарь', verbose_name='Частота синхронизации (минуты)')),
            ],
            options={
                'verbose_name': 'Синхронизация iCal',
                'verbose_name_plural': 'Синхронизации iCal',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Для отображения на карте', max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Для отображения на карте', max_digits=9, null=True, verbose_name='Долгота')),
                ('property_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('room', 'Комната'), ('studio', 'Студия'), ('villa', 'Вилла')], default='apartment', max_length=50, verbose_name='Тип недвижимости')),
                ('bedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во спален')),
                ('beds', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во кроватей')),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Кол-во ванных')),
                ('sqft', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Площадь (кв.м)')),
                ('max_guests', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Макс. гостей')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Базовая цена за ночь')),
                ('weekend_price', models.DecimalField(blank=True, decimal_places=2, help_text='Если не указано, используется базовая цена', max_digits=10, null=True, verbose_name='Цена на выходные')),
                ('weekly_discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка за неделю (%)')),
                ('monthly_discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка за месяц (%)')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Главное фото')),
                ('is_verified', models.BooleanField(default=False, help_text='Верифицированное жилье поднимается выше в поиске', verbose_name='Проверено')),
                ('is_published', models.BooleanField(default=False, help_text='Только проверенные объявления могут быть опубликованы', verbose_name='Опубликовано')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата верификации')),
                ('moderation_status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус модерации')),
                ('moderation_notes', models.TextField(blank=True, verbose_name='Заметки модератора')),
                ('booking_type', models.CharField(choices=[('instant', 'Мгновенное бронирование'), ('request', 'По запросу (требуется подтверждение)')], default='request', max_length=20, verbose_name='Тип бронирования')),
                ('house_rules', models.TextField(blank=True, help_text='Правила, которые должны соблюдать гости', verbose_name='Правила дома')),
                ('check_in_time', models.TimeField(default='14:00', verbose_name='Время заезда')),
                ('check_out_time', models.TimeField(default='12:00', verbose_name='Время выезда')),
                ('min_nights', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Мин. ночей')),
                ('max_nights', models.IntegerField(default=365, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Макс. ночей')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-is_verified', '-list_date'],
            },
        ),
        migrations.CreateModel(
            name='ListingAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.amenity')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Удобство объекта',
                'verbose_name_plural': 'Удобства объектов',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('cleanliness_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Чистота')),
                ('communication_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Коммуникация')),
                ('location_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Расположение')),
                ('value_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Соотношение цена/качество')),
                ('is_verified', models.BooleanField(default=True, help_text='Отзыв от реального гостя', verbose_name='Верифицирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RentalObject',
        ),
        migrations.AddField(
            model_name='icalsync',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ical_syncs', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='availability',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='message',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='listings.booking', verbose_name='Бронирование'),
        ),
        migrations.AddField(
            model_name='message',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='listings.listing', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='listings.booking', verbose_name='Бронирование'),
        ),
        migrations.AddField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'is_published', 'is_verified'], name='listings_li_city_d4bef6_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['latitude', 'longitude'], name='listings_li_latitud_6dd1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'check_in', 'check_out', 'status'], name='listings_bo_listing_e5744d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest', 'status'], name='listings_bo_guest_i_ef7653_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['listing', 'date', 'is_available'], name='listings_av_listing_68e214_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('listing', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='listingamenity',
            unique_together={('listing', 'amenity')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient'], name='listings_me_sender__dff3be_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['booking'], name='listings_me_booking_dbc7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['listing', 'rating'], name='listings_re_listing_bc67c1_idx'),
        ),
    ]
